import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@context/AuthContext";
import { AnimatePresence } from "framer-motion";
import { Topbar } from "@/components/app-topbar";

export const metadata: Metadata = {
  title: "ICUR Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll antialiased min-h-screen">
        <AuthProvider>
          <AnimatePresence mode="wait">{children}</AnimatePresence>
        </AuthProvider>
      </body>
    </html>
  );
}
