import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@context/AuthContext";
import { AnimatePresence } from "framer-motion";
import { Topbar } from "@/components/app-topbar";

export const metadata: Metadata = {
  title: "ICUR Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll antialiased min-h-screen">
        <AuthProvider>
          <AnimatePresence mode="wait">
            <div className="flex flex-col min-h-screen">
              {/* Topbar */}
              <Topbar />
              {/* Main Content */}
              <main className="flex flex-1 justify-center items-center px-6 py-10">
                <div
                  className="w-full max-w-7xl  rounded-2xl 
                  text-slate-100"
                >
                  {children}
                </div>
              </main>
            </div>
          </AnimatePresence>
        </AuthProvider>
      </body>
    </html>
  );
}
