import type { Metadata } from "next";
import { Topbar } from "@/components/app-topbar";
import { useAuth } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "ICUR Dashboard",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <div className="flex flex-col min-h-screen">
      {/* Topbar */}
      <Topbar />
      {/* Main Content */}
      <main className="flex flex-1 justify-center items-center px-6 py-10">
        <div
          className="w-full max-w-7xl  rounded-2xl 
                  text-slate-100"
        >
          {children}
        </div>
      </main>
    </div>
  );
}
